
// ****************************************************************************
//
//                                 Game levels
//
// ****************************************************************************

#include "../include.h"

#define TB(tile1, tile2) ((tile1) | ((tile2)<<4))

// level scenes
const u8 Levels[(LEVNUM+1)*(MAPW/2)*MAPH] = {
// 0
	TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),
	TB(CRY,CRY),TB(CRY,CRY),TB(CRY,TRE),TB(TRE,TRE),TB(EMP,EMP),TB(EMP,CRO),TB(EMP,EMP),TB(CAK,APL),TB(EMP,EMP),TB(EMP,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(CAK,APL),TB(APL,EMP),TB(EMP,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,CRO),TB(EMP,EMP),TB(EMP,CRO),TB(CAK,APL),TB(EMP,APL),TB(EMP,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(TRE,TRE),TB(EMP,CRO),TB(EMP,EMP),TB(EMP,CRO),TB(CAK,APL),TB(EMP,APL),TB(EMP,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,CRO),TB(CRO,CRO),TB(CRO,CRO),TB(CAK,APL),TB(EMP,APL),TB(EMP,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,CRO),TB(EMP,EMP),TB(EMP,CRO),TB(CAK,APL),TB(EMP,EMP),TB(APL,APL),
	TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,CRO),TB(EMP,EMP),TB(EMP,CRO),TB(CAK,APL),TB(EMP,EMP),TB(EMP,APL),
	TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),
	TB(LOC,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),
	TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(LEM,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 1
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 2
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 3
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,CRY),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,CRO),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(TRE,EMP),TB(LEM,EMP),TB(TRE,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,CRY),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),TB(EMP,EMP),TB(TRE,EMP),TB(LEM,EMP),TB(TRE,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 4
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,APL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(APL,APL),TB(APL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,APL),TB(APL,LEM),TB(APL,APL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(APL,APL),TB(TRE,WAL),TB(TRE,APL),TB(APL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(EMP,APL),TB(APL,TRE),TB(APL,WAL),TB(APL,TRE),TB(APL,APL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(APL,APL),TB(TRE,APL),TB(APL,APL),TB(APL,APL),TB(TRE,APL),TB(APL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 5
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,LEM),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,COW),TB(EMP,WAL),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,COW),TB(EMP,WAL),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,EMP),TB(EMP,WAL),
	TB(GAT,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,COW),TB(EMP,WAL),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CRO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 6
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,LEM),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CHE,CHE),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(CHE,CRO),TB(CHE,CHE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CHE,CHE),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(GAT,EMP),TB(EMP,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 7
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(TRE,LEM),TB(TRE,EMP),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,TRE),TB(EMP,POL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(POL,EMP),TB(POL,TRE),TB(EMP,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,TRE),TB(EMP,POL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,TRE),TB(POL,EMP),TB(POL,TRE),TB(EMP,EMP),TB(COW,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(TRE,EMP),TB(EMP,EMP),TB(EMP,COW),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 8
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,APL),TB(EMP,GIR),TB(EMP,APL),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,POL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 9
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,TRE),TB(TRE,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,ICE),TB(ICE,EMP),TB(WAL,EMP),TB(EMP,CRY),TB(CRY,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,WAL),TB(EMP,ICE),TB(ICE,EMP),TB(WAL,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,WAL),TB(EMP,ICE),TB(ICE,EMP),TB(WAL,EMP),TB(CRY,CRY),TB(CRY,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,ICE),TB(ICE,EMP),TB(WAL,EMP),TB(EMP,CRY),TB(CRY,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 10
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,ICE),TB(EMP,ICE),TB(EMP,ICE),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(ICE,EMP),TB(ICE,EMP),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CRO),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,POL),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,GAT),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,GIR),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(COW,EMP),TB(WAL,CAK),TB(WAL,EMP),TB(COW,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,CRY),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,CRY),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,CRY),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,LEM),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,LEM),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 11
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,POL),TB(EMP,WAL),TB(WAL,EMP),TB(POL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,COM),TB(COM,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COM),TB(COM,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,COM),TB(COM,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COM),TB(COM,EMP),TB(WAL,EMP),TB(EMP,CRO),TB(CRO,EMP),TB(EMP,WAL),TB(EMP,COM),TB(COM,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,COM),TB(EMP,EMP),TB(EMP,GAT),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,EMP),TB(EMP,EMP),TB(COM,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COM),TB(EMP,WAL),TB(TRE,WAL),TB(COM,EMP),TB(EMP,COM),TB(WAL,TRE),TB(WAL,EMP),TB(COM,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COM),TB(EMP,WAL),TB(TRE,WAL),TB(EMP,COM),TB(COM,EMP),TB(WAL,TRE),TB(WAL,EMP),TB(COM,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(EMP,WAL),TB(TRE,WAL),TB(EMP,COM),TB(COM,EMP),TB(WAL,TRE),TB(WAL,EMP),TB(COM,COM),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(EMP,WAL),TB(TRE,WAL),TB(COM,COM),TB(COM,COM),TB(WAL,TRE),TB(WAL,EMP),TB(COM,COM),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 12
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,LOC),TB(COW,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(CAK,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CAK),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,LEM),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(WAL,CAR),TB(CAR,CAR),TB(CAR,EMP),TB(CAR,CAR),TB(CAR,CAR),TB(CAR,WAL),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(WAL,CAR),TB(CAR,CAR),TB(CAR,EMP),TB(CAR,CAR),TB(CAR,CAR),TB(CAR,WAL),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CAR),TB(CAR,CAR),TB(CAR,EMP),TB(CAR,CAR),TB(CAR,CAR),TB(CAR,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 13
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(ICE,ICE),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,APL),TB(APL,WAL),
	TB(WAL,WAL),TB(ICE,ICE),TB(ICE,WAL),TB(EMP,EMP),TB(EMP,BAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,APL),TB(APL,WAL),
	TB(WAL,WAL),TB(ICE,LEM),TB(ICE,WAL),TB(EMP,EMP),TB(BAL,EMP),TB(BAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(EMP,EMP),TB(EMP,BAL),TB(EMP,GIR),TB(TRE,CRO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(COW,TRE),TB(WAL,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(GIR,TRE),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(COW,TRE),TB(WAL,WAL),TB(WAL,CRY),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(CAK,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(GIR,TRE),TB(WAL,WAL),TB(WAL,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(WAL,WAL),TB(WAL,CRY),TB(EMP,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(EMP,APL),TB(APL,WAL),
	TB(WAL,EMP),TB(COW,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(CAR,CAR),TB(CAR,EMP),TB(EMP,APL),TB(APL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 14
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,CLO),TB(CLO,CLO),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CLO,EMP),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CLO,EMP),TB(EMP,CLO),TB(EMP,CLO),TB(CLO,EMP),TB(EMP,EMP),TB(CLO,CLO),TB(CLO,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CLO,EMP),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(GAT,LOC),TB(CLO,EMP),TB(EMP,CLO),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CLO,CLO),TB(CLO,EMP),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,EMP),TB(CLO,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,EMP),TB(CLO,EMP),TB(CLO,CLO),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,CLO),TB(CLO,EMP),TB(CLO,EMP),TB(CLO,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CLO),TB(EMP,EMP),TB(CLO,EMP),TB(CLO,EMP),TB(CLO,EMP),TB(CLO,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 15
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,CRO),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,ELE),TB(TRE,ELE),TB(EMP,EMP),TB(EMP,EMP),TB(POL,TRE),TB(POL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(ELE,TRE),TB(EMP,WAL),TB(CHE,EMP),TB(TRE,POL),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(GAT,WAL),TB(WAL,WAL),TB(COM,APL),TB(WAL,CAR),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(ICE,APL),TB(WAL,ICE),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(GIR,TRE),TB(CAK,WAL),TB(ICE,CAK),TB(TRE,COW),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,GIR),TB(TRE,GIR),TB(CAK,CAK),TB(CAK,CAK),TB(COW,TRE),TB(COW,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 16
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,GLA),TB(GLA,GLA),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(GAT,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CRY),TB(WAL,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CRY),TB(WAL,CRY),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(CRO,CRO),TB(CRO,CRO),TB(CRO,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 17
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,CRY),TB(CRO,CRY),TB(CRO,CAR),TB(CAR,CAR),TB(CAR,CAR),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRO),TB(CRY,CRO),TB(CRY,WAL),TB(WAL,WAL),TB(WAL,MON),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRY),TB(CRO,WAL),TB(CRO,WAL),TB(MON,MON),TB(MON,MON),TB(WAL,MON),TB(MON,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRO),TB(CRY,CRO),TB(CRY,WAL),TB(MON,WAL),TB(WAL,WAL),TB(WAL,MON),TB(WAL,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRY),TB(CRO,CRY),TB(CRO,WAL),TB(MON,MON),TB(MON,MON),TB(MON,MON),TB(WAL,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(CRY,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(MON,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRY),TB(CRO,CRY),TB(CRO,WAL),TB(MON,MON),TB(MON,MON),TB(WAL,MON),TB(MON,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRO),TB(WAL,WAL),TB(CRY,WAL),TB(MON,WAL),TB(WAL,MON),TB(MON,MON),TB(MON,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRY),TB(CRO,CRY),TB(CRO,WAL),TB(MON,MON),TB(MON,WAL),TB(WAL,WAL),TB(MON,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRO),TB(CRY,CRO),TB(CRY,WAL),TB(MON,MON),TB(MON,MON),TB(MON,MON),TB(MON,MON),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 18
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,EMP),TB(EMP,WAL),TB(AIR,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(AIR,WAL),TB(EMP,EMP),TB(EMP,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,CAK),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,ICE),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,CAK),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,GIR),TB(EMP,EMP),TB(CRY,EMP),TB(ICE,ICE),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,LOC),TB(CAK,CAK),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,ELE),TB(EMP,EMP),TB(CRY,EMP),TB(ICE,ICE),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,CAK),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,ICE),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(ICE,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAK,EMP),TB(EMP,WAL),TB(AIR,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(AIR,WAL),TB(EMP,EMP),TB(EMP,ICE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 19
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,LOC),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(GAT,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 20
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,CRO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,ELE),TB(ELE,ELE),TB(ELE,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,TRE),TB(GIR,TRE),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(TRE,GIR),TB(TRE,GIR),TB(TRE,GIR),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,TRE),TB(GIR,TRE),TB(GIR,TRE),TB(GIR,TRE),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,GIR),TB(TRE,GIR),TB(TRE,GIR),TB(TRE,GIR),TB(TRE,WAL),TB(CRY,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(GIR,TRE),TB(GIR,LEM),TB(GIR,TRE),TB(GIR,GAT),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,CHE),TB(APL,CHE),TB(APL,CHE),TB(APL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,APL),TB(CHE,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 21
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(TRE,LEM),TB(TRE,WAL),
	TB(WAL,EMP),TB(COM,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,COM),TB(EMP,WAL),
	TB(WAL,CLO),TB(EMP,CAK),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(CAK,EMP),TB(CLO,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,ICE),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,ICE),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(ICE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,CRY),TB(CRY,EMP),TB(EMP,WAL),TB(ICE,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,ICE),TB(WAL,EMP),TB(EMP,CRY),TB(CRY,WAL),
	TB(WAL,CRY),TB(WAL,CRY),TB(EMP,EMP),TB(WAL,ICE),TB(EMP,GLA),TB(GLA,EMP),TB(ICE,WAL),TB(EMP,EMP),TB(CRY,WAL),TB(CRY,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,GLA),TB(GLA,EMP),TB(WAL,EMP),TB(EMP,CRY),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRO,EMP),TB(WAL,CRY),TB(EMP,EMP),TB(WAL,GLA),TB(GLA,WAL),TB(EMP,EMP),TB(CRY,WAL),TB(EMP,CRO),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(CRY,EMP),TB(EMP,GLA),TB(GLA,EMP),TB(EMP,CRY),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,GAT),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 22
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,LOC),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(EMP,TRE),TB(WAL,TRE),TB(EMP,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,EMP),TB(TRE,TRE),TB(LEM,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(LEM,TRE),TB(TRE,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,EMP),TB(TRE,EMP),TB(WAL,EMP),TB(TRE,EMP),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,EMP),TB(TRE,TRE),TB(TRE,TRE),TB(EMP,TRE),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,TRE),TB(EMP,TRE),TB(EMP,TRE),TB(TRE,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(TRE,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,EMP),TB(TRE,TRE),TB(TRE,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(POL,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,TRE),TB(EMP,WAL),
	TB(WAL,EMP),TB(TRE,TRE),TB(TRE,TRE),TB(WAL,EMP),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,EMP),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(TRE,TRE),TB(TRE,WAL),
	TB(GAT,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(WAL,TRE),TB(TRE,TRE),TB(GIR,TRE),TB(TRE,TRE),TB(WAL,EMP),TB(TRE,EMP),TB(TRE,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 23
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,GLA),TB(GLA,GLA),TB(GLA,EMP),TB(EMP,GLA),TB(GLA,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(GLA,WAL),TB(WAL,WAL),TB(WAL,GLA),TB(EMP,GLA),TB(GLA,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(GLA,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GLA),TB(GLA,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(GLA,WAL),TB(WAL,BAL),TB(BAL,BAL),TB(WAL,WAL),TB(WAL,WAL),TB(GLA,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(GLA,WAL),TB(WAL,BAL),TB(AIR,BAL),TB(ICE,ICE),TB(ICE,WAL),TB(GLA,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(TRE,WAL),
	TB(WAL,EMP),TB(GLA,WAL),TB(WAL,BAL),TB(BAL,BAL),TB(ICE,LEM),TB(ICE,WAL),TB(GLA,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,EMP),TB(GLA,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(ICE,ICE),TB(ICE,WAL),TB(GLA,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(TRE,WAL),
	TB(WAL,EMP),TB(GLA,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(ICE,ICE),TB(WAL,WAL),TB(GLA,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(TRE,WAL),
	TB(WAL,EMP),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,EMP),TB(TRE,EMP),TB(TRE,EMP),TB(TRE,GAT),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 24
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,POL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,GIR),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,LOC),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(APL,EMP),TB(APL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(TRE,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,EMP),TB(EMP,WAL),TB(APL,APL),TB(APL,APL),TB(APL,APL),TB(APL,WAL),TB(EMP,EMP),TB(EMP,CHE),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 25
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,LOC),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,WAL),
	TB(WAL,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(CRO,EMP),TB(EMP,CRO),TB(EMP,CRO),TB(EMP,CRO),TB(EMP,CRO),TB(EMP,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,EMP),TB(CRO,EMP),TB(EMP,CRO),TB(EMP,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,CAK),TB(CAK,WAL),TB(CAK,CAK),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(GAT,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 26
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(APL,EMP),TB(CHE,EMP),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(GIR,ELE),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,TRE),TB(TRE,POL),TB(GLA,APL),TB(WAL,CHE),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(ELE,GIR),TB(ELE,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(WAL,TRE),TB(POL,GLA),TB(APL,WAL),TB(CHE,EMP),TB(WAL,WAL),
	TB(WAL,WAL),TB(GIR,ELE),TB(GIR,EMP),TB(EMP,TRE),TB(WAL,EMP),TB(EMP,WAL),TB(TRE,POL),TB(GLA,APL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,WAL),TB(ELE,GIR),TB(ELE,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(POL,GLA),TB(APL,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(EMP,TRE),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(TRE,POL),TB(GLA,APL),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(POL,GLA),TB(APL,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(TRE,POL),TB(GLA,WAL),
	TB(WAL,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(POL,WAL),
	TB(WAL,TRE),TB(LOC,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,GAT),TB(LEM,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 27
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,LOC),TB(CRY,WAL),TB(WAL,EMP),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(WAL,CRY),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,CRY),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,EMP),TB(CRY,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,CRY),TB(WAL,GAT),TB(WAL,EMP),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(WAL,CRO),TB(EMP,CRY),TB(EMP,WAL),TB(CRY,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(WAL,EMP),TB(WAL,EMP),TB(CRY,WAL),TB(EMP,WAL),TB(CRY,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,EMP),TB(WAL,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(CRY,EMP),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 28
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,WAL),TB(WAL,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,WAL),
	TB(WAL,LOC),TB(WAL,GIR),TB(GIR,GIR),TB(EMP,EMP),TB(EMP,ELE),TB(ELE,EMP),TB(EMP,EMP),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(EMP,GIR),TB(ELE,ELE),TB(ELE,ELE),TB(WAL,EMP),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 29
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,GIR),TB(EMP,WAL),TB(EMP,COW),TB(EMP,EMP),TB(WAL,EMP),TB(ELE,EMP),TB(WAL,EMP),TB(GIR,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,EMP),TB(WAL,WAL),TB(WAL,EMP),TB(WAL,WAL),TB(LOC,WAL),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,TRE),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(TRE,EMP),TB(EMP,EMP),TB(TRE,EMP),TB(EMP,EMP),TB(TRE,WAL),
	TB(WAL,LEM),TB(EMP,EMP),TB(EMP,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(TRE,EMP),TB(EMP,EMP),TB(TRE,EMP),TB(EMP,EMP),TB(LEM,WAL),
	TB(WAL,WAL),TB(WAL,EMP),TB(WAL,WAL),TB(WAL,EMP),TB(WAL,WAL),TB(GAT,WAL),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COW),TB(EMP,WAL),TB(EMP,ELE),TB(EMP,WAL),TB(EMP,EMP),TB(GIR,EMP),TB(WAL,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 30
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(CLO,CLO),TB(CLO,CLO),TB(CLO,WAL),TB(WAL,CRY),TB(CRY,CRY),TB(CRY,CRY),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,POL),TB(POL,WAL),TB(WAL,CRO),TB(CRO,CRO),TB(WAL,CRO),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(ICE,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,APL),TB(APL,WAL),TB(WAL,APL),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(AIR,CAR),TB(WAL,WAL),TB(CAR,WAL),TB(WAL,COM),TB(WAL,WAL),TB(COM,COM),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(CAK,CAK),TB(CAK,WAL),TB(CAK,WAL),TB(WAL,COW),TB(WAL,COW),TB(COW,COW),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(BAL,BAL),TB(BAL,BAL),TB(BAL,WAL),TB(WAL,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,TRE),TB(TRE,WAL),TB(WAL,TRE),TB(TRE,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 31
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,TRE),TB(TRE,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,TRE),TB(TRE,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,LOC),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,TRE),TB(TRE,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,TRE),TB(TRE,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,EMP),TB(CRY,TRE),TB(TRE,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 32
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),
	TB(WAL,LOC),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,WAL),
	TB(WAL,TRE),TB(LEM,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,LEM),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,LEM),TB(WAL,TRE),TB(TRE,WAL),
	TB(WAL,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,GAT),
	TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,WAL),
	TB(WAL,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),
	TB(WAL,WAL),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),TB(WAL,TRE),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 33
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(ICE,WAL),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(CAK,EMP),TB(EMP,CHE),TB(CHE,CHE),TB(CHE,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(ICE,WAL),TB(WAL,WAL),TB(ICE,EMP),TB(CAK,WAL),TB(WAL,CAK),TB(EMP,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,ICE),TB(WAL,ICE),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,ICE),TB(WAL,ICE),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(CHE,CHE),TB(CHE,EMP),TB(LEM,GAT),
	TB(WAL,EMP),TB(EMP,ICE),TB(WAL,ICE),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(WAL,CHE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,ICE),TB(WAL,ICE),TB(EMP,CAK),TB(WAL,WAL),TB(WAL,WAL),TB(CAK,CHE),TB(WAL,WAL),TB(CHE,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(ICE,WAL),TB(WAL,WAL),TB(ICE,EMP),TB(CAK,WAL),TB(WAL,CAK),TB(EMP,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(ICE,WAL),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(CAK,EMP),TB(EMP,CHE),TB(WAL,WAL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 34
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GLA),TB(GLA,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(GLA,GLA),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 35
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,CRO),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,GAT),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(COW,EMP),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,COW),TB(COW,EMP),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,WAL),TB(COW,COW),TB(COW,EMP),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(COW,COW),TB(COW,EMP),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,COW),TB(COW,EMP),TB(GIR,GIR),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(COW,EMP),TB(GIR,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,TRE),TB(TRE,TRE),TB(LEM,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,LEM),TB(TRE,TRE),TB(TRE,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 36
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(LOC,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,CRO),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,CRY),TB(EMP,WAL),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),

// 37
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CHE),TB(APL,APL),TB(APL,CHE),TB(CHE,APL),TB(APL,APL),TB(CHE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(WAL,CHE),TB(APL,WAL),TB(APL,CHE),TB(CHE,APL),TB(WAL,APL),TB(CHE,WAL),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,APL),TB(APL,WAL),TB(APL,APL),TB(APL,APL),TB(WAL,APL),TB(APL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(CRY,EMP),TB(TRE,APL),TB(WAL,WAL),TB(WAL,APL),TB(APL,WAL),TB(WAL,WAL),TB(APL,TRE),TB(EMP,CRY),TB(EMP,GAT),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,APL),TB(APL,WAL),TB(APL,APL),TB(APL,APL),TB(WAL,APL),TB(APL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CRY,EMP),TB(WAL,CHE),TB(APL,WAL),TB(APL,CHE),TB(CHE,APL),TB(WAL,APL),TB(CHE,WAL),TB(EMP,CRY),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CHE),TB(APL,APL),TB(APL,CHE),TB(CHE,APL),TB(APL,APL),TB(CHE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,CHE),TB(CHE,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 38
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(LEM,EMP),TB(EMP,LEM),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,AIR),TB(EMP,EMP),TB(EMP,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,EMP),TB(EMP,EMP),TB(AIR,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,TRE),TB(WAL,EMP),TB(EMP,WAL),TB(TRE,EMP),TB(EMP,WAL),TB(TRE,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(TRE,EMP),TB(EMP,EMP),TB(WAL,TRE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,TRE),TB(WAL,TRE),TB(EMP,TRE),TB(EMP,EMP),TB(WAL,EMP),TB(TRE,EMP),TB(TRE,WAL),TB(TRE,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(TRE,WAL),TB(EMP,EMP),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(WAL,WAL),TB(EMP,EMP),TB(WAL,TRE),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(TRE,GAT),
	TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 39
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,COM),TB(COM,COM),TB(COM,COM),TB(COM,WAL),TB(EMP,EMP),TB(COM,COM),TB(COM,COM),TB(COM,COM),TB(COM,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,COM),TB(COM,WAL),TB(EMP,EMP),TB(COM,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,COM),TB(COM,WAL),TB(EMP,EMP),TB(COM,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,COM),TB(COM,WAL),TB(COM,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(COM,COM),TB(COM,WAL),TB(EMP,EMP),TB(EMP,COM),TB(COM,COM),TB(COM,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COM),TB(COM,WAL),TB(COM,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COM),TB(COM,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COM,COM),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,COM),TB(COM,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,COM),TB(COM,COM),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(COM,COM),TB(COM,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,GAT),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 40
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,TRE),TB(TRE,LEM),TB(TRE,TRE),TB(TRE,APL),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(TRE,TRE),TB(TRE,TRE),TB(APL,APL),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(APL,APL),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(LOC,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(APL,APL),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(APL,APL),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,COW),TB(COW,COW),TB(WAL,COW),TB(COW,COW),TB(APL,APL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(APL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,COW),TB(COW,COW),TB(COW,COW),TB(COW,COW),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 41
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,GIR),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(ELE,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,POL),TB(WAL,EMP),TB(EMP,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),TB(POL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(LOC,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(GAT,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 42
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,CAK),TB(GAT,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(ICE,ICE),TB(ICE,ICE),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,EMP),TB(ICE,ICE),TB(ICE,ICE),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(COW,ICE),TB(ICE,GIR),TB(GIR,GIR),TB(GIR,GIR),TB(GIR,ICE),TB(ICE,COW),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(COW,ICE),TB(ICE,ELE),TB(ELE,ELE),TB(ELE,ELE),TB(ELE,ICE),TB(ICE,COW),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(ICE,ICE),TB(ICE,ICE),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(ICE,ICE),TB(ICE,ICE),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,CAK),TB(LOC,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(ICE,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 43
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(CLO,EMP),TB(EMP,EMP),TB(POL,WAL),TB(CHE,EMP),TB(EMP,EMP),TB(APL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,CLO),TB(EMP,WAL),TB(POL,WAL),TB(CHE,WAL),TB(EMP,APL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(CLO,EMP),TB(POL,WAL),TB(CHE,EMP),TB(APL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,CLO),TB(POL,WAL),TB(CHE,APL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,LOC),TB(TRE,TRE),TB(LEM,TRE),TB(TRE,TRE),TB(EMP,GAT),TB(EMP,TRE),TB(TRE,TRE),TB(LEM,TRE),TB(TRE,TRE),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,APL),TB(CHE,WAL),TB(POL,CLO),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(APL,EMP),TB(CHE,WAL),TB(POL,EMP),TB(CLO,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(WAL,APL),TB(EMP,WAL),TB(CHE,WAL),TB(POL,WAL),TB(EMP,CLO),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(APL,EMP),TB(WAL,WAL),TB(CHE,WAL),TB(POL,WAL),TB(WAL,EMP),TB(CLO,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,APL),TB(EMP,EMP),TB(EMP,EMP),TB(CHE,EMP),TB(POL,EMP),TB(EMP,EMP),TB(EMP,CLO),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 44
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(EMP,TRE),TB(TRE,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(TRE,TRE),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,TRE),TB(EMP,TRE),TB(WAL,WAL),TB(TRE,EMP),TB(LEM,TRE),TB(EMP,WAL),
	TB(WAL,TRE),TB(WAL,WAL),TB(WAL,EMP),TB(TRE,TRE),TB(EMP,EMP),TB(TRE,EMP),TB(WAL,WAL),TB(EMP,TRE),TB(EMP,EMP),TB(TRE,WAL),
	TB(WAL,TRE),TB(WAL,EMP),TB(TRE,LEM),TB(TRE,WAL),TB(EMP,TRE),TB(WAL,TRE),TB(WAL,EMP),TB(TRE,WAL),TB(TRE,WAL),TB(EMP,GAT),
	TB(WAL,LOC),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,TRE),TB(WAL,TRE),TB(EMP,WAL),TB(TRE,WAL),TB(WAL,TRE),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,EMP),TB(TRE,EMP),TB(WAL,WAL),TB(TRE,WAL),TB(TRE,EMP),TB(WAL,TRE),TB(WAL,TRE),TB(EMP,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,TRE),TB(EMP,WAL),TB(WAL,EMP),TB(TRE,EMP),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

#if 0

// 45
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(ICE,ICE),TB(EMP,LOC),TB(EMP,EMP),TB(CAK,CAK),TB(EMP,EMP),TB(EMP,EMP),TB(CHE,CHE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,ICE),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(CAK,EMP),TB(EMP,CHE),TB(WAL,WAL),TB(CHE,EMP),TB(EMP,WAL),
	TB(WAL,ICE),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(CAK,EMP),TB(EMP,CHE),TB(WAL,WAL),TB(CHE,EMP),TB(EMP,WAL),
	TB(GAT,EMP),TB(ICE,ICE),TB(EMP,EMP),TB(EMP,EMP),TB(CAK,CAK),TB(EMP,EMP),TB(EMP,EMP),TB(CHE,CHE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(ICE,ICE),TB(EMP,EMP),TB(EMP,EMP),TB(CAK,CAK),TB(EMP,EMP),TB(EMP,EMP),TB(APL,APL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,ICE),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(CAK,EMP),TB(EMP,APL),TB(WAL,WAL),TB(APL,EMP),TB(EMP,WAL),
	TB(WAL,ICE),TB(WAL,WAL),TB(ICE,EMP),TB(EMP,CAK),TB(WAL,WAL),TB(CAK,EMP),TB(EMP,APL),TB(WAL,WAL),TB(APL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(ICE,ICE),TB(EMP,EMP),TB(EMP,EMP),TB(CAK,CAK),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 46
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,LOC),TB(EMP,ELE),TB(EMP,WAL),TB(COW,COW),TB(WAL,EMP),TB(GIR,EMP),TB(GIR,EMP),TB(GIR,EMP),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(ELE,EMP),TB(ELE,WAL),TB(COW,GIR),TB(WAL,EMP),TB(EMP,ELE),TB(EMP,ELE),TB(EMP,EMP),TB(WAL,TRE),TB(POL,WAL),
	TB(WAL,EMP),TB(EMP,LEM),TB(EMP,WAL),TB(COW,COW),TB(EMP,EMP),TB(EMP,EMP),TB(COW,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,ELE),TB(EMP,EMP),TB(EMP,WAL),TB(ELE,COW),TB(COW,EMP),TB(GIR,EMP),TB(EMP,EMP),TB(GIR,EMP),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(ELE,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,ELE),TB(EMP,ELE),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(EMP,ELE),TB(EMP,ELE),TB(EMP,ELE),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,ELE),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(TRE,EMP),TB(EMP,EMP),TB(ELE,EMP),TB(ELE,EMP),TB(EMP,GIR),TB(GIR,GIR),TB(WAL,ELE),TB(ELE,EMP),TB(EMP,WAL),
	TB(WAL,POL),TB(POL,WAL),TB(ELE,EMP),TB(EMP,LEM),TB(EMP,EMP),TB(EMP,EMP),TB(GIR,GIR),TB(WAL,ELE),TB(ELE,ELE),TB(EMP,WAL),
	TB(GAT,TRE),TB(TRE,WAL),TB(EMP,ELE),TB(EMP,EMP),TB(ELE,EMP),TB(EMP,WAL),TB(GIR,GIR),TB(WAL,ELE),TB(LEM,ELE),TB(ELE,WAL),
	TB(WAL,POL),TB(POL,WAL),TB(ELE,EMP),TB(ELE,EMP),TB(EMP,EMP),TB(GIR,WAL),TB(GIR,GIR),TB(WAL,ELE),TB(ELE,ELE),TB(ELE,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 47
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,GLA),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GLA),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAR,CAR),TB(CAR,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(CAR,CAR),TB(CAR,CAR),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAR,CAR),TB(CAR,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(CAR,CAR),TB(CAR,CAR),TB(EMP,WAL),
	TB(WAL,LOC),TB(WAL,WAL),TB(WAL,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAR,CAR),TB(CAR,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(CAR,CAR),TB(CAR,CAR),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,WAL),TB(WAL,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(CAR,CAR),TB(CAR,GLA),TB(WAL,CAR),TB(WAL,AIR),TB(WAL,CAR),TB(WAL,GLA),TB(CAR,CAR),TB(CAR,CAR),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,GAT),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 48
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,WAL),TB(APL,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,APL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,WAL),TB(APL,EMP),TB(WAL,TRE),TB(WAL,COW),TB(COW,WAL),TB(TRE,WAL),TB(EMP,APL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,EMP),TB(CHE,WAL),TB(APL,EMP),TB(WAL,ELE),TB(ELE,WAL),TB(WAL,ELE),TB(ELE,WAL),TB(EMP,APL),TB(WAL,CHE),TB(EMP,WAL),
	TB(WAL,LOC),TB(WAL,WAL),TB(WAL,EMP),TB(ICE,ELE),TB(LEM,POL),TB(POL,LEM),TB(ELE,ICE),TB(EMP,WAL),TB(WAL,WAL),TB(EMP,GAT),
	TB(WAL,EMP),TB(APL,WAL),TB(CHE,EMP),TB(WAL,ELE),TB(ELE,WAL),TB(WAL,ELE),TB(ELE,WAL),TB(EMP,CHE),TB(WAL,APL),TB(EMP,WAL),
	TB(WAL,EMP),TB(APL,WAL),TB(CHE,EMP),TB(WAL,TRE),TB(WAL,COW),TB(COW,WAL),TB(TRE,WAL),TB(EMP,CHE),TB(WAL,APL),TB(EMP,WAL),
	TB(WAL,EMP),TB(APL,WAL),TB(CHE,EMP),TB(WAL,GIR),TB(GIR,GIR),TB(GIR,GIR),TB(GIR,WAL),TB(EMP,CHE),TB(WAL,APL),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 49
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,LOC),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,TRE),TB(WAL,WAL),TB(TRE,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,TRE),TB(WAL,WAL),TB(TRE,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,TRE),TB(EMP,WAL),TB(WAL,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,WAL),TB(WAL,EMP),TB(TRE,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(WAL,AIR),TB(TRE,EMP),TB(WAL,TRE),TB(TRE,WAL),TB(WAL,TRE),TB(TRE,WAL),TB(EMP,TRE),TB(AIR,WAL),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,WAL),TB(AIR,TRE),TB(EMP,TRE),TB(LEM,WAL),TB(WAL,LEM),TB(TRE,EMP),TB(TRE,AIR),TB(WAL,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(WAL,AIR),TB(TRE,EMP),TB(WAL,TRE),TB(TRE,WAL),TB(EMP,TRE),TB(AIR,WAL),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),TB(AIR,TRE),TB(WAL,TRE),TB(TRE,WAL),TB(TRE,AIR),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(COW,EMP),TB(EMP,EMP),TB(WAL,CAR),TB(CAR,CAR),TB(CAR,CAR),TB(CAR,WAL),TB(EMP,EMP),TB(EMP,COW),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,COW),TB(EMP,EMP),TB(EMP,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,EMP),TB(EMP,EMP),TB(COW,EMP),TB(EMP,WAL),
	TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,GAT),TB(WAL,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,EMP),TB(EMP,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

// 50
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,COW),TB(CHE,POL),TB(GIR,ICE),TB(CAK,COM),TB(CAR,BAL),TB(CLO,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(CAK,WAL),TB(WAL,WAL),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,WAL),TB(CHE,POL),TB(GIR,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(GAT,CRY),TB(CRO,TRE),TB(APL,WAL),TB(CHE,POL),TB(GIR,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,LOC),TB(CRO,TRE),TB(APL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,COW),TB(CHE,POL),TB(WAL,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,COW),TB(CHE,POL),TB(WAL,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,WAL),TB(CHE,POL),TB(WAL,ICE),TB(CAK,WAL),TB(EMP,EMP),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,WAL),TB(WAL,WAL),TB(WAL,ICE),TB(CAK,WAL),TB(WAL,WAL),TB(WAL,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,CRY),TB(CRO,TRE),TB(APL,COW),TB(CHE,POL),TB(GIR,ICE),TB(CAK,COM),TB(CAR,BAL),TB(CLO,ELE),TB(GLA,MON),TB(AIR,WAL),
	TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),TB(WAL,WAL),

#endif
};

// level paswords
const char LevelPsw[(LEVNUM+1)*PSWLEN+1] =
	"INTRO"		// 0 
	"GOLEM"		// 1 
	"KRONE"		// 2 
	"MYDLO"		// 3 
	"LEDEN"		// 4 
	"STROP"		// 5 
	"LILIE"		// 6 
	"RYBKA"		// 7 
	"KLAUN"		// 8 
	"BRAUN"		// 9 
	"WHITE"		// 10
	"MOUSE"		// 11
	"DREAM"		// 12
	"IDEAL"		// 13
	"ILUZE"		// 14
	"SAINT"		// 15
	"BELLS"		// 16
	"TROJA"		// 17
	"EMOCE"		// 18
	"BASTL"		// 19
	"ISLAM"		// 20
	"JEANS"		// 21
	"METAL"		// 22
	"MIKRO"		// 23
	"SENZA"		// 24
	"GALAX"		// 25
	"STONE"		// 26
	"SLAVE"		// 27
	"FORTE"		// 28
	"LUCIE"		// 29
	"NATUR"		// 30
	"BIENE"		// 31
	"KATZE"		// 32
	"HYDRO"		// 33
	"FAUNA"		// 34
	"ULTRA"		// 35
	"TODAY"		// 36
	"HOROR"		// 37
	"GAPPA"		// 38
	"RETAL"		// 39
	"CLOCK"		// 40
	"HOMER"		// 41
	"BUNNY"		// 42
	"FOTON"		// 43
	"QUACK"		// 44
	"HAFIK"		// 45
/*
	"DIZZY"		// 46
	"STARK"		// 47
	"ZARAZ"		// 48
	"DUKEN"		// 49
	"STORY"		// 50
*/
	;

#if 0
// Level solution
const char* const Solution[LEVNUM+1] = {
	// 0: RRRRRRRRRRRRRRRRRRRULLLLLLLLLL
	"RRRRRRRRRRRRRRRRRRRDLLLLLLLLLL",

	// 1: RRRR RRRR RRRR RRUU ULLL LLLL LLLL DDDD DDRR RRRR RDRR RRRR RR
	"RRRRRRRRRRRRRRUUULLLLLLLLLLLDDDD"
	"DDRRRRRRRDRRRRRRRR",

	// 2: UURR RRRR RRRU LLLL LLUR RRRR RULL LLLL URRR RRRR DDDD DDLL LLDD
	"UURRRRRRRRRULLLLLLURRRRRRULLLLLL"
	"URRRRRRRDDDDDDLLLLDD",

	// 3: UUUL URRU LLUR RULU RRRR RRRR RRRR RDDD DDDL UUUU LDDD DLUU UULD DDLL L
	"UUULURRULLURRULURRRRRRRRRRRRRDDD"
	"DDDLUUUULDDDDLUUUULDDDLLL",

	// 4: RRRDDDDDRRRRRRRRRRULLLLURRULLLLDDLLLURRUURRRULLLLLLLLLUUUURRRRRRRDRRRRRRRRULLLLLLLU
	"RRRDDDDDRRRRRRRRRRULLLLURRULLLLD"
	"DLLLURRUURRRULLLLLLLLLUUUURRRRRR"
	"RDRRRRRRRRULLLLLLLU",

	// 5: RRDDDRRRRULLLURRRULLLLURRRRULLLLLURRRRRRRRRRRRRRRDLDDDDDLUUUULDDDDLUUUULDDDDDDLLLLLLLLLLLUUL
	"RRDDDRRRRULLLURRRULLLLURRRRULLLL"
	"LURRRRRRRRRRRRRRRDLDDDDDLUUUULDD"
	"DDLUUUULDDDDDDLLLLLLLLLLLUUL",

	// 6: RRRRRDDDRRRRRULLLLURRRRULLLLURRRRULLLLURRRURRRRRDDDDDDDDDLLLLLLLLLLLLLLL
	"RRRRRDDDRRRRRULLLLURRRRULLLLURRR"
	"RULLLLURRRURRRRRDDDDDDDDDLLLLLLL"
	"LLLLLLLL",

	// 7: RRRRDDLLDDRRRRRULURRRRDLDRRRRRRRUULLLULLLLLLLURRRRRRRRRRUULLLLLLDLULDLULDLULLUURRRRRU
	"RRRRDDLLDDRRRRRULURRRRDLDRRRRRRR"
	"UULLLULLLLLLLURRRRRRRRRRUULLLLLL"
	"DLULDLULDLULLUURRRRRU",

	// 8: DDDDRRUUUUUUUURRRRRRDDDLLDDDDRRRRULLLURRRULLURULUURRRRRRDDDDDDDDDLLLLLL
	"DDDDRRUUUUUUUURRRRRRDDDLLDDDDRRR"
	"RULLLURRRULLURULUURRRRRRDDDDDDDD"
	"DLLLLLL",

	// 9: UUUUURDDDDDRRRRUURRRULLLURRRULLLURRRRUUULLLLLLLLDLULLLLLLLLDDDDRRRRDLLLDRRRDLLDDRRRRRRD
	"UUUUURDDDDDRRRRUURRRULLLURRRULLL"
	"URRRRUUULLLLLLLLDLULLLLLLLLDDDDR"
	"RRRDLLLDRRRDLLDDRRRRRRD",

	// 10: DDDDDRRUUUUUUUUURRRRRRRRDLLLDRDLLLDDDDDDRRRRRRRRRURULURULURULURULULLLDDDDDDDDDLLLUUUUU
	"DDDDDRRUUUUUUUUURRRRRRRRDLLLDRDL"
	"LLDDDDDDRRRRRRRRRURULURULURULURU"
	"LULLLDDDDDDDDDLLLUUUUU",

	// 11: RRDDDLDRDRRRUUUUULLULURURRURRDRRRURRRRDDRDLDRDDDRDLDLLLUUUUULULLLDDRRDLLDRRDLLLUUUUL
	"RRDDDLDRDRRRUUUUULLULURURRURRDRR"
	"RURRRRDDRDLDRDDDRDLDLLLUUUUULULL"
	"LDDRRDLLDRRDLLLUUUUL",

	// 12: DDDDDRRUUUUURRRRRRDDDLLLLDDRURDRURDRURDRURDRUULLLLLUULLLLLLDDDLUUUUUUURRRRRRRRRRRRRRRDDDLLDRRDDDRUUUUUUUULLLLLLLLLU
	"DDDDDRRUUUUURRRRRRDDDLLLLDDRURDR"
	"URDRURDRURDRUULLLLLUULLLLLLDDDLU"
	"UUUUUURRRRRRRRRRRRRRRDDDLLDRRDDD"
	"RUUUUUUUULLLLLLLLLU",

	// 13: RRUULUURDRDDDLLLDDDDDRURURRURRURRURRULLLUURRDRRDRUUURRRRRDLLLDDDRRRDDLLDDRRDLLLLUUULLLDRRDDLULLULDDLULDD
	"RRUULUURDRDDDLLLDDDDDRURURRURRUR"
	"RURRULLLUURRDRRDRUUURRRRRDLLLDDD"
	"RRRDDLLDDRRDLLLLUUULLLDRRDDLULLU"
	"LDDLULDD",

	// 14: UUUURRDLDDDRRRUUUURRDDDDRRRULULURURRRDDRRRRRRDDDDLDRDDLLUUULLDDDLUUULDDDLLLUURULLLLLLLLLUUL
	"UUUURRDLDDDRRRUUUURRDDDDRRRULULU"
	"RURRRDDRRRRRRDDDDLDRDDLLUUULLDDD"
	"LUUULDDDLLLUURULLLLLLLLLUUL",

	// 15: RRUUUURRRRRRDDRDRDDDLDLLUURULULLLURRRRRRRRRDLLLDDDRRRDLLLLLLLLLURRRURULULLLURRRRUULLLLLLDDDDR
	"RRUUUURRRRRRDDRDRDDDLDLLUURULULL"
	"LURRRRRRRRRDLLLDDDRRRDLLLLLLLLLU"
	"RRRURULULLLURRRRUULLLLLLDDDDR",

	// 16: UUUUURRRDRDRDRDRRURURURURRDDDDDDLLLLLDRDDLLLLUURULLLLLUUUUUURRRRDRRRRDLLLDRDD
	"UUUUURRRDRDRDRDRRURURURURRDDDDDD"
	"LLLLLDRDDLLLLUURULLLLLUUUUUURRRR"
	"DRRRRDLLLDRDD",

	// 17: DDDDRURDRUUULLUULUUUURDDDRDRUUULURRRRRRDDLLLDDRRRRRUURRDDDLDLDLLULLLDDDRURDRRRRUURDDD
	"DDDDRURDRUUULLUULUUUURDDDRDRUUUL"
	"URRRRRRDDLLLDDRRRRRUURRDDDLDLDLL"
	"ULLLDDDRURDRRRRUURDDD",

	// 18: DDDDRRRUUUURRRRDRDDDLLLURDRRRRRUULDDLLUUURUUULUUULLLDDRUURRDDDDLLLLLLUUULDDDDDDDRUUURRRRRRRRRRRDDDDRRRUUUUUUUULDDDDDDLUUUULDLLLLLUUUURRDRUR
	"DDDDRRRUUUURRRRDRDDDLLLURDRRRRRU"
	"ULDDLLUUURUUULUUULLLDDRUURRDDDDL"
	"LLLLLUUULDDDDDDDRUUURRRRRRRRRRRD"
	"DDDRRRUUUUUUUULDDDDDDLUUUULDLLLL"
	"LUUUURRDRUR",

	// 19: DDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUURDDDDDRRRRRRRRRRRULLLLLLLLLLURRRRRRRRRRULLLLLLLLLLURRRRRRRRRRULLLLLLLLLURRRRRRRRRULLLLLLLLLURRRRRRRRRULLLLLLLLL
	"DDDDDRUUUUURDDDDDRUUUUURDDDDDRUU"
	"UUURDDDDDRRRRRRRRRRRULLLLLLLLLLU"
	"RRRRRRRRRRULLLLLLLLLLURRRRRRRRRR"
	"ULLLLLLLLLURRRRRRRRRULLLLLLLLLUR"
	"RRRRRRRRULLLLLLLLLLLLLLLLLDRRRRR"
	"RRDLLLLLLLDRRRRRRRD",

	// 20: RRRRRRDRRRURURRRDRDLLULDLDRRRRRDLLLLLLULLULULULDLLDDDDRRRDLLLLLUUUUUUUURRRRRRRRRRRRRRRRRDDDDDDDDLUU
	"RRRRRRDRRRURURRRDRDLLULDLDRRRRRD"
	"LLLLLLULLULULULDLLDDDDRRRDLLLLLU"
	"UUUUUUURRRRRRRRRRRRRRRRRDDDDDDDD"
	"LUU",

	// 21: LDDRDDLLULULULULULLDDDDDRRULULUURRDRDRDRDRRRUUULLULULULULLLUURDRURDRDRDRDRDRRRURURURURURRRDDLULDLDLDLDLDLLDDDRRRURURURURRDDLDDRR
	"LDDRDDLLULULULULULLDDDDDRRULULUU"
	"RRDRDRDRDRRRUUULLULULULULLLUURDR"
	"URDRDRDRDRDRRRURURURURURRRDDLULD"
	"LDLDLDLDLLDDDRRRURURURURRDDLDDRR",

	// 22: DDDDDDRRRRUUURRDDDDDRRRUURUULLDRDDDRRRUUUUUUURDDRDDDDRDDRRULURULLURRULLURRULLLURRRULLLLLLLDRDRDDDDDDDLLLLLLUUUUUUURRUULDLULLLLLDRRRRDLLLLDRRDLLDRRRDDLLLLDRRRDLLLL
	"DDDDDDRRRRUUURRDDDDDRRRUURUULLDR"
	"DDDRRRUUUUUUURDDRDDDDRDDRRULURUL"
	"LURRULLURRULLLURRRULLLLLLLDRDRDD"
	"DDDDDLLLLLLUUUUUUURRUULDLULLLLLD"
	"RRRRDLLLLDRRDLLDRRRDDLLLLDRRRDLL"
	"LL",

	// 23: DDDDDRRRRRRRUUULLLUURRDRRRDDLDDRRRUUUUUULULULULLLLLDLDLDDDDDDDRRRRRRUUULLLUURDRRRRDLDDDRRRRRUUULUUUULULURRRDDDDDRRRRDLLLDRRRDLLDRRR
	"DDDDDRRRRRRRUUULLLUURRDRRRDDLDDR"
	"RRUUUUUULULULULLLLLDLDLDDDDDDDRR"
	"RRRRUUULLLUURDRRRRDLDDDRRRRRUUUL"
	"UUUULULURRRDDDDDRRRRDLLLDRRRDLLD"
	"RRR",

	// 24: DDLLULUULLLLLUURRRUUULLDRRDDLLLDDRRRRRDDRDRRRRURUURRRRRRUULLLLUUURRRRDLLLLDDRRRRDDLLLLLLDDLDLLLLULUULLLLLDDDDRRRUULDLULUURRRRRDDRDRRRRURUURRRRRRDDDDLLLLUURDRURRUULLLLLLDDLDLLUUURUUUUULLDRDLDRDLDRDDLLLDDRRURRURRDDLLLD
	"DDLLULUULLLLLUURRRUUULLDRRDDLLLD"
	"DRRRRRDDRDRRRRURUURRRRRRUULLLLUU"
	"URRRRDLLLLDDRRRRDDLLLLLLDDLDLLLL"
	"ULUULLLLLDDDDRRRUULDLULUURRRRRDD"
	"RDRRRRURUURRRRRRDDDDLLLLUURDRURR"
	"UULLLLLLDDLDLLUUURUUUUULLDRDLDRD"
	"LDRDDLLLDDRRURRURRDDLLLD",

	// 25: RRRRRRRRRRRRRRRRRDLDDDDDDDDLUUUUUUULULLLLLLLLLLLLLDDDDDDDDRUUUUUUURRDDDDDDDRUUUUUUURRRRRRRRDDDDDDDLUUUUUULLDDDDDDLUUUUUULLDDDDDDD
	"RRRRRRRRRRRRRRRRRDLDDDDDDDDLUUUU"
	"UUULULLLLLLLLLLLLLDDDDDDDDRUUUUU"
	"UURRDDDDDDDRUUUUUUURRRRRRRRDDDDD"
	"DDLUUUUUULLDDDDDDLUUUUUULLDDDDDD"
	"D",

	// 26: LURURURURURURURURRRDRDRDRDRDRDRDRUUUUULULULULLLLLLLLLDDLLULLDRDLDRRURRRURURRRRRDRDRDRDRDDDRDL
	"LURURURURURURURURRRDRDRDRDRDRDRD"
	"RUUUUULULULULLLLLLLLLDDLLULLDRDL"
	"DRRURRRURURRRRRDRDRDRDRDDDRDL",

	// 27: RDRDDLLDDRRRDDDDLLLUURRRUULLLUURRRRUUURRDDDDDLDDRRDRDLLUULUURUUURRURURRRRRRDDDDDRDLDLDLUUUULLDDDLUULLU
	"RDRDDLLDDRRRDDDDLLLUURRRUULLLUUR"
	"RRRUUURRDDDDDLDDRRDRDLLUULUURUUU"
	"RRURURRRRRRDDDDDRDLDLDLUUUULLDDD"
	"LUULLU",

	// 28: UUUURRRRRRRDRRRDDDRRDDRDRURULLURRULULDLDLLDLULDLLLDLDLULURRULLURURDRDRRUUUUR
	"UUUURRRRRRRDRRRDDDRRDDRDRURULLUR"
	"RULULDLDLLDLULDLLLDLDLULURRULLUR"
	"URDRDRRUUUUR",

	// 29: DRRUUULDRDDLLLLLDDDDDLUURUU UUUUURRDDLLDD LLLLUUUULLDD RRDDDDDLLDDRRRULUUUURRRRRRRRRRRRRUULUURRRDDLULDDDD DDRRDDLULDLUURUURRULLLDLLLLLLLLLLLLLLURRRRRRRRRRRDDDDLLUU
	"DRRUUULDRDDLLLLLDDDDDLUURUUUUUUU"
	"RRDDLLDDLLLLUUUULLDDRRDDDDDLLDDR"
	"RRULUUUURRRRRRRRRRRRRUULUURRRDDL"
	"ULDDDDDDRRDDLULDLUURUURRULLLDLLL"
	"LLLLLLLLLLLURRRRRRRRRRRDDDDLLUU",

	// 30: RRRRRRUULULULUUURRDRDRDDDDD RRRUUUUURURURRDDDLDLDLDDRRRRRUUUUUUUUULLLLLLLLLLLLLLLDDDDDDDDDRRRRRUULLLUUUUURRRRDDDDDDDRRRUUUUUUURRRRDDDDDLLLDDRRRRRRR
	"RRRRRRUULULULUUURRDRDRDDDDDRRRUU"
	"UUURURURRDDDLDLDLDDRRRRRUUUUUUUU"
	"ULLLLLLLLLLLLLLLDDDDDDDDDRRRRRUU"
	"LLLUUUUURRRRDDDDDDDRRRUUUUUUURRR"
	"RDDDDDLLLDDRRRRRRR",

	// 31: RRRRRRRRRRRRRRRRR DDDDLLLLLLLLLLLLLLLLL UUUUUURRRRRRRRRRRRRRRRRDDDDDDLLLLLLLLLLLLLLLLL UUUURRRRRRRRRRRRRRRRR UUUULLLLLLLLLLLLLLLLLDDDDDDRRRRRRRRRRRRRRRRR DDLLLLLLLLLD
	"RRRRRRRRRRRRRRRRRDDDDLLLLLLLLLLL"
	"LLLLLLUUUUUURRRRRRRRRRRRRRRRRDDD"
	"DDDLLLLLLLLLLLLLLLLLUUUURRRRRRRR"
	"RRRRRRRRRUUUULLLLLLLLLLLLLLLLLDD"
	"DDDDRRRRRRRRRRRRRRRRRDDLLLLLLLLL"
	"D",

	// 32: UUUURDLDDDDDDRDRDRRRULULULULUURURURURRRDLDLDLDDRDRDRDRDRRRULULULULUURURURURRRDLDLDLDDRDRDRDRDRRRULULULULUURURUURDRDDLDDRDR
	"UUUURDLDDDDDDRDRDRRRULULULULUURU"
	"RURURRRDLDLDLDDRDRDRDRDRRRULULUL"
	"ULUURURURURRRDLDLDLDDRDRDRDRDRRR"
	"ULULULULUURURUURDRDDLDDRDR",

	// 33: UUUURDDRDDRRUURUURRRRRDRDDDDDDDLDLLLLLUULUULLDDLDDLUUUUURRRRRRUUURURRRRRRRRRDDDDDLLLLDDDDLLLLLULUUULLLLDDLDDLUUURULURULUUURDDRDDRRRRUUURURRRRRDDDDDRRDRDRDDRUUUUR
	"UUUURDDRDDRRUURUURRRRRDRDDDDDDDL"
	"DLLLLLUULUULLDDLDDLUUUUURRRRRRUU"
	"URURRRRRRRRRDDDDDLLLLDDDDLLLLLUL"
	"UUULLLLDDLDDLUUURULURULUUURDDRDD"
	"RRRRUUURURRRRRDDDDDRRDRDRDDRUUUU"
	"R",

	// 34: LLLLDRDRDRDRDRURURURURURRRRDDDDDDDDDLLUUUUUUUUULLLLDLLLLLDRRRRDLLDDDLDLDLDRRURURURDRDRDLLULDLD
	"LLLLDRDRDRDRDRURURURURURRRRDDDDD"
	"DDDDLLUUUUUUUUULLLLDLLLLLDRRRRDL"
	"LDDDLDLDLDRRURURURDRDRDLLULDLD",

	// 35: DDDDRRRRRRDRRUURURURULULULLDLDLDRDRUURRDLDDDDLLLLLLLLUUUUUUUUURRRRRRRRRRRRRRRRRDDDDDDDDDLLLLLLLLLUULUUUUURU
	"DDDDRRRRRRDRRUURURURULULULLDLDLD"
	"RDRUURRDLDDDDLLLLLLLLUUUUUUUUURR"
	"RRRRRRRRRRRRRRRDDDDDDDDDLLLLLLLL"
	"LUULUUUUURU",

	// 36: DDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUUURRDDDDDDDDDRRUUUUUUUURRULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLUUUUUUUUULLDDDDDDDDDLLURRUUUUUUURRDDDDDDDRRUUUUUUURRDDDDDDDRRUUUUUUURRDDDDDDDRDD
	"DDDDDDDDDRRUUUUUUUUURRDDDDDDDDDR"
	"RUUUUUUUUURRDDDDDDDDDRRUUUUUUUUU"
	"RRDDDDDDDDDRRUUUUUUUURRULLDDDDDD"
	"DDDLLUUUUUUUUULLDDDDDDDDDLLUUUUU"
	"UUUULLDDDDDDDDDLLUUUUUUUUULLDDDD"
	"DDDDDLLURRUUUUUUURRDDDDDDDRRUUUU"
	"UUURRDDDDDDDRRUUUUUUURRDDDDDDDRD"
	"D",

	// 37: RRRRURUURRDDRRRUURRDDRDRRUUUURRDLDRDLDRDLDRDLDRDLLUUUUULLULUULLDDLLLUULLDDLDLLUUUULLDRDLDRDLDRDLDRDLDRRUUUUURRUUUURRRRRRRRRDDLULLLLDRDDLDLDRDLLLUULDDDRRRRRUUURDDDRURDRUULURURRRRR
	"RRRRURUURRDDRRRUURRDDRDRRUUUURRD"
	"LDRDLDRDLDRDLDRDLLUUUUULLULUULLD"
	"DLLLUULLDDLDLLUUUULLDRDLDRDLDRDL"
	"DRDLDRRUUUUURRUUUURRRRRRRRRDDLUL"
	"LLLDRDDLDLDRDLLLUULDDDRRRRRUUURD"
	"DDRURDRUULURURRRRR",

	// 38: UUUURRRRRRRRDDDLDDDDDDLURURULUUURRRDDDDDRDLLURUUURRDRDDDRRULULULULULULLLDLDLDLDDDLLURURURRRUUURRDDRDRRULULULUULLLDLDLDLDLDLDLUUUUURRUURRRRRRRDRURRRRRDDLULLLDRDRDRDRDRDRDR
	"UUUURRRRRRRRDDDLDDDDDDLURURULUUU"
	"RRRDDDDDRDLLURUUURRDRDDDRRULULUL"
	"ULULULLLDLDLDLDDDLLURURURRRUUURR"
	"DDRDRRULULULUULLLDLDLDLDLDLDLUUU"
	"UURRUURRRRRRRDRURRRRRDDLULLLDRDR"
	"DRDRDRDRDR",

	// 39: RRRRRDDDDDLLLDDDDLLURUUUURULURULLURRRDRRDRDDLDDDDDRUUURDDDRUUURDDDRRUUUURRUURRUULLLLLLULLLLLLLLLDDDDDDDDDRUUUUUUUURDDDDRRRDDDRRRRRUUUUUURDDDRRDDDRRDRRR
	"RRRRRDDDDDLLLDDDDLLURUUUURULURUL"
	"LURRRDRRDRDDLDDDDDRUUURDDDRUUURD"
	"DDRRUUUURRUURRUULLLLLLULLLLLLLLL"
	"DDDDDDDDDRUUUUUUUURDDDDRRRDDDRRR"
	"RRUUUUUURDDDRRDDDRRDRRR",

	// 40: RURURURURRRRRRDDDDDLDLDLLUR URURULURULLLLDLDLDLDLD RRURURURURDDLDLDDLLLLDRRRRRRD
	"RURURURURRRRRRDDDDDLDLDLLURURURU"
	"LURULLLLDLDLDLDLDRRURURURURDDLDL"
	"DDLLLLDRRRRRRD",

	// 41: RRUUUUUUUUULLLLLDDDDDDDDDRRRRRRRUUUUUUUUULLLLLLLLLDDDDDDDDDRRRRUUURDDDRRRRRRUUUUUUUUULLLLLLDDDDDLUUUUULLLLLLDDDDDDDDDRRRRRRUUURDDDRRRRRRRRUUUUUUUUULLLLLLLLDDDDDLUUUUULLLLLLLLDDDDDDDDDRRRRRRRRUUURDDDD
	"RRUUUUUUUUULLLLLDDDDDDDDDRRRRRRR"
	"UUUUUUUUULLLLLLLLLDDDDDDDDDRRRRU"
	"UURDDDRRRRRRUUUUUUUUULLLLLLDDDDD"
	"LUUUUULLLLLLDDDDDDDDDRRRRRRUUURD"
	"DDRRRRRRRRUUUUUUUUULLLLLLLLDDDDD"
	"LUUUUULLLLLLLLDDDDDDDDDRRRRRRRRU"
	"UURDDDD",

	// 42: LURULURULLURUULURURDRDLDDRDRURDRURDRURDDDLDRDRURULUURULULURULUR
	"LURULURULLURUULURURDRDLDDRDRURDR"
	"URDRURDDDLDRDRURULUURULULURULUR",

	// 43: DDDDDRRRURURURUUUULULULLLLDDDDDDDDDRRRRRRRRRRRRRRRRUUUUUUUUULLLLDLDLDDDDRDRDRDLLLLLLUUUUUUUUULLLLLLLDDDDRRRRRRDDLDLDLDRRRRRRUUUURURRRRRUUUULLLLLLDDDDL
	"DDDDDRRRURURURUUUULULULLLLDDDDDD"
	"DDDRRRRRRRRRRRRRRRRUUUUUUUUULLLL"
	"DLDLDDDDRDRDRDLLLLLLUUUUUUUUULLL"
	"LLLLDDDDRRRRRRDDLDLDLDRRRRRRUUUU"
	"RURRRRRUUUULLLLLLDDDDL",

	// 44: UUURURRRDDDLLDDDDRRURUUUURRURDDLDDDDDRRURUUUUULURURRRDRDLDLDDDDDRRURUUUUUURRDDR
	"UUURURRRDDDLLDDDDRRURUUUURRURDDL"
	"DDDDDRRURUUUUULURURRRDRDLDLDDDDD"
	"RRURUUUUUURRDDR",

	// 45: RRRRRRRRRRRRDDDLLDDDRRRDDDLLURULULLLDDDLLLLLLLLLLLLUUURUUURDDDRDDRRRUURUUURDDDRDDRRRUURUUURRUUULLLDDLLLUULLLDDLLLUULLLDDDL
	"RRRRRRRRRRRRDDDLLDDDRRRDDDLLURUL"
	"ULLLDDDLLLLLLLLLLLLUUURUUURDDDRD"
	"DRRRUURUUURDDDRDDRRRUURUUURRUUUL"
	"LLDDLLLUULLLDDLLLUULLLDDDL",

	// 46: DDRDRDRDDRDRDRDRRUUURUULUURRDRRURRRRRUULDDLLLLDLLULLDDRDDDDLDLLULULULUUUUUULLLDRRDLLDDRRRDDRDRDRDRRURUUUULUURRDRRURRDDRRRDDDDDLLLURRULLURRULLULLURUUULDDLUULDLULDDLLUULDDDRRRRRDLDDRRRDDDLUULLLUULLLLDRRRDLDRRRDLLLLLLURULULLLDRDDLUL
	"DDRDRDRDDRDRDRDRRUUURUULUURRDRRU"
	"RRRRRUULDDLLLLDLLULLDDRDDDDLDLLU"
	"LULULUUUUUULLLDRRDLLDDRRRDDRDRDR"
	"DRRURUUUULUURRDRRURRDDRRRDDDDDLL"
	"LURRULLURRULLULLURUUULDDLUULDLUL"
	"DDLLUULDDDRRRRRDLDDRRRDDDLUULLLU"
	"ULLLLDRRRDLDRRRDLLLLLLURULULLLDR"
	"DDLUL",

	// 47: DDDDRRRRRRRRUUUUUUUUULLDDDDDDDDDRRRRUUUUUUUUULLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRUUUUUUUUULLLLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRURDRURDRURUUUUUUUULLLLLLLLLLLLLDDDDDDDDDRRRRRRRRURDRURDRURUUUUUUUULLLLLLLLLLLLLLLLLDDDDDDDDDRRRRRRRRRRRRRRRRRULLLLLUURRRRRUULLLLLUURRRRRUULLLLLLLLLLLLLLLLLDDRRRRDDLLLLDDRRRRDDLLLLDRRRRRRRRD
	"DDDDRRRRRRRRUUUUUUUUULLDDDDDDDDD"
	"RRRRUUUUUUUUULLLLLLLLLLDDDDDDDDD"
	"RRRRRRRRRRRRUUUUUUUUULLLLLLLLLLL"
	"LDDDDDDDDDRRRRRRRRRRRRURDRURDRUR"
	"UUUUUUUULLLLLLLLLLLLLDDDDDDDDDRR"
	"RRRRRRURDRURDRURUUUUUUUULLLLLLLL"
	"LLLLLLLLLDDDDDDDDDRRRRRRRRRRRRRR"
	"RRRULLLLLUURRRRRUULLLLLUURRRRRUU"
	"LLLLLLLLLLLLLLLLLDDRRRRDDLLLLDDR"
	"RRRDDLLLLDRRRRRRRRD",

	// 48: UUUURRRRDDDDRRRRRRRRRURUUURRDDDRDDDDDLLLLUUUU LLDLULLLULDLLULUUULLDDDLDDRDDLDDRURDRRUULUURURRUUURRDRURRDDLDLLLDLDDRRURDRRUUURRDRDDDRRUUURUR
	"UUUURRRRDDDDRRRRRRRRRURUUURRDDDR"
	"DDDDDLLLLUUUULLDLULLLULDLLULUUUL"
	"LDDDLDDRDDLDDRURDRRUULUURURRUUUR"
	"RDRURRDDLDLLLDLDDRRURDRRUUURRDRD"
	"DDRRUUURUR",

	// 49: LLDDDDDDDRRUURDDRRUUUUUUURRRRRRDDDDDDDDDLLLLLURRRRULLURRUURUUUULLDDDLDLDLDLUULURUURULLLDDLUULLLDRDDRDLDDLULULULUUULLDDDDDDRDDRDRRRRRR
	"LLDDDDDDDRRUURDDRRUUUUUUURRRRRRD"
	"DDDDDDDDLLLLLURRRRULLURRUURUUUUL"
	"LDDDLDLDLDLUULURUURULLLDDLUULLLD"
	"RDDRDLDDLULULULUUULLDDDDDDRDDRDR"
	"RRRRR",

	// 50: RURRDLDRRRRDDLULLLLULDDDDRUURRDLDRRRRRRUUUUUULLLURRRURDDDDDDDDRRRRRRRRULLLURRRULLLURRRULLLURRRULLLURRRULLLLLLLLLLLLLLLLLDRRRDLLLDL
	"RURRDLDRRRRDDLULLLLULDDDDRUURRDL"
	"DRRRRRRUUUUUULLLURRRURDDDDDDDDRR"
	"RRRRRRULLLURRRULLLURRRULLLURRRUL"
	"LLURRRULLLLLLLLLLLLLLLLLDRRRDLLL"
	"DL",
};
#endif


