TARGET=CH32PROG
DEVICE=picopad10
DEVCLASS=picopad

# ASM source files
ASRC +=

# C source files
CSRC += src/power.c
CSRC += src/swio.c
CSRC += src/ardulink.c
CSRC += src/minichlink.c
CSRC += src/chipinfo.c
CSRC += src/erase.c
CSRC += src/flash.c

# C++ source files
SRC += src/main.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
#PICO_ROOT_PATH =

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
